# Generated by Django 4.1 on 2023-05-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_hackathon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
