# Generated by Django 4.2 on 2023-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackathons',
            field=models.ManyToManyField(blank=True, related_name='participants', to='base.hackathon'),
        ),
    ]
